### ISSUE TITLE
Does not work when run from a tmux session inside termial

### ISSUE THREAD

**Issue by justrajdeep** [chrisbra/vpager#2]
Hi

This works when I run it from inside regular terminal, but does not work when I run it from inside a tmux terminal in vim.

How to repro:

Launch vim,

Open a terminal inside vim: `:terminal`
run a command to test if vpager is working: `ls | vpager`
Create a new tmux session: `tmux new -s test`

run a command in the new tmux session: ` ls | vpager`

Thanks in advance :)

**Comment by chrisbra** [comment]
you are creating a tmux session inside the vim terminal?

**Comment by justrajdeep** [comment]
Yes, creating a tmux session inside vim terminal.

**Comment by justrajdeep** [comment]
But it really does not matter, it can be an existing tmux session attached to that terminal inside vim.

**Comment by chrisbra** [comment]
yes, but your tmux session must then take over the `VIM_TERMINAL` environment variable. Can you check if this variable is there?

**Comment by justrajdeep** [comment]
This is what i get

With TMUX
` echo $VIM_TERMINAL`
`VIM_TERMINAL: Undefined variable.`

Without TMUX
`echo $VIM_TERMINAL`
`802`

**Comment by chrisbra** [comment]
Hm,
not sure. tmux should inherit the exported variables. If not, please export it manually in the tmux session and I think this should work then. There is probably a way to make tmux automatically inherit those variables, but I do not know.
