### ISSUE TITLE
color code escape sequences

### ISSUE THREAD

**Issue by Konfekt** [chrisbra/vpager#5]
In the animated gif, it seems as the highlighting in the terminal carries over seamlessly to the buffer in vim. However, here only the escape sequences are shown. Any ideas why things work well on your setup but less so here?

**Comment by chrisbra** [comment]
Are you talking about the diff output? I think this is because on the commandline we explicitly set the filetype to `:set diff`

**Comment by Konfekt** [comment]
Oh, okay. So from the terminal there were never colorized characters piped into vpager?

**Comment by Konfekt** [comment]
Right now I pipe those through `sed -r "s/\x1B(\[[0-9;]*[JKmsu]|\(B)//g"` as well

**Comment by chrisbra** [comment]
I don't stip them explicitly. Usually, terminal programs shouldn't output those when called with a pipe. What program does emit them even through a pipe?

I think you may also pipe them through `col -b` to get rid of it.

**Comment by Konfekt** [comment]
Thank you, for some reason `l` was aliased to `ls --color` instead of `ls --color=auto`
